name: Github pages deploy

on:
  push:	
    branches:	
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Deploy
      env: 
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        npm ci
        npm run-script ng deploy -- --no-silent --cname=https://mydata.webtree.org --name="Webtree CI/CD tools" --email="cicd@webtree.org"
